exports.up = function (knex) {
  return knex.raw(`
    CREATE TABLE app.hospital (
      hospital_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
      name text NOT NULL,
      location text NOT NULL
    );
  `);
};

exports.down = function (knex) {
  return knex.raw(`DROP TABLE app.hospital;`);
};
