exports.up = function (knex) {
  return knex.raw(`
    CREATE TABLE app.doctor (
      doctor_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
      first_name text NOT NULL,
      last_name text NOT NULL,
      middle_initial char,
      email text NOT NULL,
      password text NOT NULL,
      license_number integer,
      specialization text,
      contact_number text
    );
  `);
};

exports.down = function (knex) {
  return knex.raw(`DROP TABLE app.doctor;`);
};
